In [1]:
import pandas as pd

In [46]:
taxonomy = pd.read_csv(
    "dada2rb-taxonomy-annotate.txt",
    sep="\t",
    header=None,
    names=["id", "taxonomy"]
)

counts = pd.read_csv(
    "dada2rb-genus-count.txt",
    sep="\t",
    index_col=0
)

In [47]:
taxonomy = taxonomy[taxonomy["id"].str.contains("genus")]

In [48]:
taxonomy["genus"] = taxonomy["taxonomy"].str.split(";").str[-1]
taxonomy.head()

,id,taxonomy,genus
865,RB_genus1,Bacteria;Acidobacteria;Acidobacteria;Acidobact...,Bryocella
866,RB_genus2,Bacteria;Acidobacteria;Acidobacteria;Acidobact...,Candidatus_Koribacter
867,RB_genus3,Bacteria;Acidobacteria;Acidobacteria;Acidobact...,Edaphobacter
868,RB_genus4,Bacteria;Acidobacteria;Acidobacteria;Acidobact...,NA
869,RB_genus5,Bacteria;Acidobacteria;Acidobacteria;Subgroup_...,NA

In [49]:
mapping = dict(
    zip(
        taxonomy["id"],
        taxonomy["genus"]
    )
)

In [52]:
counts = counts.rename(columns=mapping)

In [53]:
counts.columns = [
    "g__" + str(x)
    for x in counts.columns
]

In [69]:
counts = counts.drop(columns=counts.filter(like="g__NA").columns)

In [71]:
counts

,g__Bryocella,g__Candidatus_Koribacter,g__Edaphobacter,g__Bryobacter,g__Candidatus_Solibacter,g__Blastocatella,g__Geothrix,g__CL500-29_marine_group,g__Illumatobacter,g__Candidatus_Microthrix,...,g__AUTHM297,g__Thermotoga,g__Opitutus,g__Lentimonas,g__Chthoniobacter,g__Candidatus_Methylacidiphilum,g__Akkermansia,g__Luteolibacter,g__Prosthecobacter,g__Roseimicrobium
SEQN,,,,,,,,,,,,,,,,,,,,,
57816.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59605.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56372.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55484.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55685.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,24,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52242.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59571.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60334.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60221.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65692.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
counts = counts.T
counts.head()

SEQN,57816.0,59605.0,56372.0,55484.0,55685.0,55743.0,71267.0,66184.0,56831.0,58573.0,...,65763.0,66735.0,67187.0,64256.0,56213.0,52242.0,59571.0,60334.0,60221.0,65692.0
g__Bryocella,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Candidatus_Koribacter,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Edaphobacter,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Bryobacter,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Candidatus_Solibacter,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
counts.to_csv(
    "NHANES_MGM_genus_counts.csv",
    index=True
)

In [2]:
tax_dict_azh = pd.read_csv(
    "taxonomy.tsv",
    sep="\t"
)
tax_dict_azh.head()

,Feature ID,Taxon,Confidence
0,afc7d633b31eacbcd06f9bd00fc92aba,d__Bacteria; p__Firmicutes; c__Negativicutes; ...,1.000000
1,d08c784d1836f43726d1162eadd9c4a4,d__Bacteria; p__Proteobacteria; c__Gammaproteo...,0.999996
2,58844abe1585eaed470c626af5e293c2,d__Bacteria; p__Bacteroidota; c__Bacteroidia; ...,1.000000
3,b9678f89d81e366818a5f4e9a4dbcbf6,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lac...,1.000000
4,2f2af02b1b3b9b47876e1c1f5c41d976,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lac...,1.000000

In [3]:
def extract_genus(tax):
    levels = str(tax).split(";")

    for level in levels:
        level = level.strip()
        if level.startswith("g__"):
            return level

    return None

tax_dict_azh["genus"] = tax_dict_azh["Taxon"].apply(extract_genus)

In [14]:
df_asv = pd.read_csv('asv_table.tsv', sep = '\t', header=1)
runs = df_asv.columns
df_asv.head()

Index(['#OTU ID', 'SRR32936402', 'SRR32936389', 'SRR32938709', 'SRR32936396',
       'SRR32936412', 'SRR32938731', 'SRR32938711', 'SRR32938723',
       'SRR32938694',
       ...
       'SRR32936387', 'SRR32938727', 'SRR32936398', 'SRR32936425',
       'SRR32936411', 'SRR32936397', 'SRR32938719', 'SRR32936399',
       'SRR32938700', 'SRR32936400'],
      dtype='object', length=102)

In [9]:
mapping_azh = dict(
    zip(
        tax_dict_azh["Feature ID"],
        tax_dict_azh["genus"]
    )
)
new_cols = df_asv.iloc[:, 0]
df_asv = df_asv.iloc[:, 1:].T
df_asv.columns = new_cols.values
df_asv = df_asv.rename(columns=mapping_azh)

df_asv = df_asv.groupby(df_asv.columns, axis=1).sum()


df_asv.head()

NameError: name 'tax_dict_azh' is not defined

In [6]:
manual_mapping = {
    'g__Cutibacterium': 'g__Propionibacterium',
    'g__Burkholderia-Caballeronia-Paraburkholderia': 'g__Burkholderia',


    "g__Pseudopropionibacterium": "g__Propionibacterium",
    "g__Eubacterium_saphenum_group": "g__Eubacterium",
    "g__Eubacterium_yurii_group": "g__Eubacterium",

    "g__Saccharimonadaceae": "g__Candidatus_Saccharimonas",
    "g__Saccharimonadales": "g__Candidatus_Saccharimonas",
    "g__TM7a": "g__Candidatus_Saccharimonas",
    "g__TM7x": "g__Candidatus_Saccharimonas",

    "g__Prevotellaceae": "g__Prevotella",
    "g__Prevotellaceae_UCG_004": "g__Prevotella",

    "g__Escherichia": "g__Escherichia_Shigella",
    "g__Shigella": "g__Escherichia_Shigella",

    "g__S24_7": "g__Muribaculaceae",
    "g__S24-7": "g__Muribaculaceae",

    "g__Bacilli_RF39": "g__RF39",
    "g__Mollicutes_RF39": "g__RF39",
    "g__Izemoplasmatales": "g__RF39",
}


df_asv.columns = (
    df_asv.columns
    .map(lambda x: manual_mapping.get(x, x))  # Aplicar el diccionario
    .str.replace("-", "_", regex=False)       # Sustituir - por _
    .str.replace("[", "", regex=False)        # Eliminar [
    .str.replace("]", "", regex=False)        # Eliminar ]
)


df_asv = df_asv.groupby(df_asv.columns, axis=1).sum()

df_asv.head()

C:\Users\Usuario\AppData\Local\Temp\ipykernel_11864\2419695742.py:39: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df_asv = df_asv.groupby(df_asv.columns, axis=1).sum()

,g__Abiotrophia,g__Absconditabacteriales_(SR1),g__Acholeplasma,g__Acinetobacter,g__Actinobacillus,g__Actinomyces,g__Aerococcus,g__Aggregatibacter,g__Alloprevotella,g__Alloscardovia,...,g__Suttonella,g__Tannerella,g__Treponema,g__UCG_004,g__UTBCD1,g__Veillonella,g__Verruc_01,g__Vicingus,g__W5053,g__uncultured
SRR32936402,417.0,0.0,0.0,0.0,7.0,9895.0,0.0,550.0,4360.0,2.0,...,0.0,94.0,23.0,0.0,0.0,18386.0,0.0,0.0,0.0,430.0
SRR32936389,323.0,264.0,0.0,0.0,1211.0,2443.0,0.0,3910.0,4805.0,6.0,...,0.0,1525.0,4056.0,0.0,0.0,4273.0,0.0,0.0,30.0,119.0
SRR32938709,11.0,0.0,0.0,0.0,3.0,4035.0,0.0,83.0,669.0,16.0,...,0.0,19.0,4.0,0.0,0.0,33407.0,0.0,0.0,0.0,323.0
SRR32936396,2.0,4.0,0.0,0.0,209.0,9130.0,0.0,429.0,550.0,3.0,...,100.0,240.0,197.0,0.0,0.0,24755.0,0.0,0.0,0.0,112.0
SRR32936412,31.0,3.0,0.0,0.0,368.0,12889.0,0.0,75.0,3300.0,9.0,...,4.0,30.0,228.0,0.0,0.0,28790.0,0.0,0.0,0.0,675.0

In [23]:
df_asv = df_asv.T
df_asv.head()

,SRR32936402,SRR32936389,SRR32938709,SRR32936396,SRR32936412,SRR32938731,SRR32938711,SRR32938723,SRR32938694,SRR32938705,...,SRR32936387,SRR32938727,SRR32936398,SRR32936425,SRR32936411,SRR32936397,SRR32938719,SRR32936399,SRR32938700,SRR32936400
g__Abiotrophia,417.0,323.0,11.0,2.0,31.0,16.0,8.0,2.0,15.0,44.0,...,21.0,148.0,2.0,27.0,44.0,46.0,338.0,204.0,13.0,3.0
g__Absconditabacteriales_(SR1),0.0,264.0,0.0,4.0,3.0,0.0,2.0,0.0,1.0,3.0,...,2.0,2.0,0.0,0.0,0.0,7.0,10.0,6.0,36.0,1.0
g__Acholeplasma,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Acinetobacter,0.0,0.0,0.0,0.0,0.0,4.0,5.0,0.0,0.0,10.0,...,0.0,0.0,2.0,3.0,6.0,0.0,2.0,0.0,0.0,0.0
g__Actinobacillus,7.0,1211.0,3.0,209.0,368.0,6.0,12.0,3.0,6.0,165.0,...,172.0,0.0,2.0,4.0,4.0,2011.0,3.0,31.0,3.0,2.0

In [24]:
df_asv.to_csv("asv_genus.csv", index=True)

In [25]:
len(list(df_asv.columns))

101

In [6]:
df_metadata = pd.read_csv('SraRunTable.csv')

df_metadata["disease_status"] = (
    df_metadata["Sample Name"]
    .str.extract(r"(Patient|Control)", expand=False)
    .str.lower()
)

df_metadata["disease_status"] = df_metadata["disease_status"].map({
    "control": 0,
    "patient": 1
})

df_metadata["pair_id"] = (
    df_metadata["Sample Name"]
    .str.extract(r"(\d+)", expand=False)
    .astype(int)
)

df_metadata = df_metadata[["Run","disease_status","pair_id"]]

df_metadata

             Run  disease_status  pair_id
0    SRR32936395               1       17
1    SRR32936396               0       16
2    SRR32936397               1        3
3    SRR32936398               1       16
4    SRR32936408               1        2
..           ...             ...      ...
247  SRR32938727               0        6
248  SRR32938728               1        6
249  SRR32938729               0        5
250  SRR32938733               1        4
251  SRR32938734               1        1

[252 rows x 3 columns]

In [18]:
df_metadata = df_metadata[df_metadata['Run'].isin(runs)]

In [19]:
df_metadata.to_csv("df_metadata.csv", index=True)